---
title: "spant SVS analysis results"
output: html_document
params:
  fit_res: ""
  argg: ""
---

```{r setup, include=FALSE}
library(spant)
library(ggplot2)
knitr::opts_chunk$set(echo = FALSE)
theme_set(theme_bw())
```

# Fit plot
```{r, fig.width=7, fig.height=6}
plot(params$fit_res)
```

# Results table
```{r}

res_tab <- sv_res_table(params$fit_res, format_out = TRUE)

amps  <- as.numeric(fit_amps(params$fit_res))
amps  <- format(amps, digits = 3)
names <- names(fit_amps(params$fit_res))
tab   <- data.frame(names, amps)

col_names <- c("amps", "CI95", "sds_perc")
kableExtra::kable_styling(kableExtra::kbl(res_tab[col_names],
                          col.names = c("Name", "Amp. (/tCr)", "95% CI (/tCr)", "SD %"),
                          align = c("r", "r", "r")),
                          full_width = FALSE,
                          position = "left",
                          bootstrap_options = c("striped", "hover",
                                                "condensed"))
```

# Provenance
```{r, echo = TRUE}
packageVersion("spant")
Sys.time()
print(argg)
```