// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// expm_cplx
Eigen::MatrixXcd expm_cplx(Eigen::MatrixXcd M);
RcppExport SEXP _spant_expm_cplx(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXcd >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(expm_cplx(M));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spant_expm_cplx", (DL_FUNC) &_spant_expm_cplx, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_spant(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
