# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

expm_cplx <- function(M) {
    .Call('_spant_expm_cplx', PACKAGE = 'spant', M)
}

